using JuMP

# READING DATA GENERATED BY THE MATLAB CODE #
y = readcsv("y.csv");
x = readcsv("x.csv");
iv = readcsv("iv.csv");

# 2SLS ESTIMATION OF HOMOGENEOUS LOGIT MODEL #
pz = iv*inv(iv'*iv)*iv';
xhat = pz*x;
PX2sls = inv(xhat'*xhat)*xhat';                     # projection matrix on weighted x-space for 2SLS
beta2sls = PX2sls*y;
se2sls = sqrt(diag( mean((y-x*beta2sls).^2)*inv(x'*pz*x)));

# Choices for GMM estimation
# GMM weighting matrix follows Nevo

expmeanval0 = exp(y);     # starting value for mean values
W = inv(iv'*iv);  # GMM weighting matrix
PX = inv(x'*iv*W*iv'*x)*x'*iv*W*iv'; # Used to calculate starting values

# MPEC ESTIMATION OF RANDOM COEFFICIENTS LOGIT MODEL #
starts = 5;
theta20 = 0.5*abs(beta2sls);
startvalues = repmat(theta20',starts,1).*hcat(ones(size(theta20)),rand(starts-1,size(theta20',2))'*1)';
nIV = size(iv,2);       # # instrumental variables
